version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: CVStoretechcombo-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ: "Asia/Kolkata"
      
    volumes:
      - /home/ubuntu/uploads:/app/uploads
      
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: CVStoretechcombo-postgres

    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: cvstore

    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./postgres-backups:/var/backups

    ports:
      - "5433:5432"

    restart: always
  

volumes:
  postgres_data:
